name: Generate Languages Card

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate languages.svg
        run: |
          mkdir -p dist

          curl -L \
          "https://SEU-LINK.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&hide_title=false&layout=compact&card_width=320&langs_count=5&theme=github_dark&hide_border=false" \
          -o dist/languages.svg

      - name: Deploy languages.svg
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: languages-output
          publish_dir: ./dist
          force_orphan: true
