name: Generate GitHub Stats

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download stats.svg
        run: |
          mkdir -p dist
          curl -L \
          "https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&include_all_commits=true&count_private=true&theme=chartreuse-dark&hide_border=false&locale=en" \
          -o dist/stats.svg

      - name: Deploy to stats-output
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: stats-output
          force_orphan: true
